/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.forms;

import proyecto.javacc.SQLparser;
import java.awt.Color;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.sql.*;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import proyecto.sql.Conexion;

/**
 *
 * @author renec
 */
public class frmParser extends javax.swing.JFrame {

    /**
     * Creates new form frmParser
     */
    
    static SQLparser parser = null;
    DefaultMutableTreeNode raiz;
    
    public frmParser() {
        raiz = new DefaultMutableTreeNode("SQL Server");
        initComponents();
        crearNodos(raiz);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dbTree = new javax.swing.JTree(raiz);
        jScrollPane3 = new javax.swing.JScrollPane();
        txtEntrada = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        lblTablas = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtTablas = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador Lexico");
        setBackground(new java.awt.Color(0, 0, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        setForeground(java.awt.Color.darkGray);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Base de Datos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Entrada de texto");

        dbTree.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dbTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                dbTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(dbTree);

        txtEntrada.setColumns(20);
        txtEntrada.setRows(5);
        jScrollPane3.setViewportView(txtEntrada);

        jButton2.setBackground(new java.awt.Color(0, 51, 153));
        jButton2.setText("Ejecutar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 51, 153));
        jButton3.setText("Analizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Salida del analizador");

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane2.setViewportView(txtSalida);

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setText("Actualizar Bases de Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblTablas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTablas.setText("Tablas de base");

        txtTablas.setEditable(false);
        txtTablas.setColumns(20);
        txtTablas.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtTablas.setRows(5);
        jScrollPane4.setViewportView(txtTablas);

        jButton4.setBackground(new java.awt.Color(0, 51, 153));
        jButton4.setText("Select");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(157, 157, 157)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)))
                    .addComponent(jLabel3))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTablas)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTablas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String entrada = txtEntrada.getText(); //Agarra todos los datos de la caja de texto
        InputStream is = new ByteArrayInputStream(entrada.getBytes()); //el parser necesita un inputstream

        if(parser == null){
            parser = new SQLparser(is); //inicializacion del parser
        } else {
            SQLparser.ReInit(is);
        }

        try{

            switch (SQLparser.inicio()){
                case 0 : //Sino se encuentra ningun erros entonces la sentencia es correcta
                txtSalida.setForeground(Color.black);
                txtSalida.setText("Sentencias correctas");
                jButton2.setEnabled(true);
                jButton4.setEnabled(true);
                break;
            }
        } catch (Exception e) {
            txtSalida.setForeground(Color.red);
            String error = "";
            if(e.getMessage().toString().contains("Was expecting:")){
                error = e.getMessage().toString().replace("Was expecting:", "Se esperaba:").replace("<EOF>", "");
                jButton2.setEnabled(false);
            } else {
                error = e.getMessage().toString().replace("Was expecting one of:", "Se esperaba uno de los siguientes:").replace("<EOF>", "");
                jButton2.setEnabled(false);
                jButton4.setEnabled(false);
            }
            txtSalida.setText("Error en la sentencia.\n" + error);
            jButton2.setEnabled(false);
            jButton4.setEnabled(false);
        } catch (Error e) {
            txtSalida.setForeground(Color.red);
            String error = e.getMessage().toString().replace("Was expecting one of:", "Se esperaba:").replace("<EOF>", "");
            error.replace("Was expecting one of:", "Se esperaba:");
            txtSalida.setText("Error en la sentencia.\n" + error);
            jButton2.setEnabled(false);
            jButton4.setEnabled(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void dbTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_dbTreeValueChanged
        String db = evt.getPaths()[0].getLastPathComponent().toString();
        lblTablas.setText(db);
        if(!db.equals("SQL Server")){
            try {
                Connection con = Conexion.getMainConnection(); 					
                con.setCatalog(db);
                Statement stmt = con.createStatement();
                ResultSet res = stmt.executeQuery("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_CATALOG='" + db + "'");
                String salida = "";
                while (res.next()) {
                   salida += "⁃ " + res.getString("TABLE_NAME") + "\n";
                }
                res.close();
                con.close();
                
                txtTablas.setText(salida);
            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_dbTreeValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        raiz.removeAllChildren();
        crearNodos(raiz);
        DefaultTreeModel model = (DefaultTreeModel) dbTree.getModel();
        model.reload();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String entrada = txtEntrada.getText();
        String salida =  "";
        
        try{
        Connection con = Conexion.getMainConnection();
        PreparedStatement query;
        query = con.prepareCall(entrada);
        int consulta2 = query.executeUpdate();
        
        if(consulta2 > 0){
        JOptionPane.showMessageDialog(this, "Ejecucion Correcta");
        txtSalida.setForeground(Color.black);
        txtSalida.setText("Sentencias ejecutadas correctamente");
        }
        else{
        JOptionPane.showMessageDialog(this, "Ejecucion correcta");
        txtSalida.setForeground(Color.black);
        txtSalida.setText("Sentencias ejecutadas correctamente");
        }
        con.close();
        }catch(Exception e){
            String error = e.getMessage();
            txtSalida.setForeground(Color.red);
            txtSalida.setText(error+"\nPrecione el boton Consulta Select para proceder.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String entrada = txtEntrada.getText();
        String salida = "";
        
        try{
        Connection con = Conexion.getMainConnection();
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery(entrada);
        
        ResultSetMetaData mdata = rs.getMetaData();
        int colCount = mdata.getColumnCount();
        Vector<String> colNombres = new Vector<String>();
        int i = 0;
        int contador = 0;
        while(i < colCount){
            i++;
            colNombres.add(mdata.getColumnName(i));
        }
        
        while(rs.next()){
            for(i = 0; i < colNombres.size(); i++){
            salida += rs.getString(colNombres.get(i))+ "\t";
            }
            contador++;
            salida += "\n";
        }
        rs.close();
        con.close();
        
        if(contador > 0){
            txtSalida.setForeground(Color.black);
            txtSalida.setText("Registros encontrados:\n" + salida);
        }
        else{
        txtSalida.setForeground(Color.black);
        txtSalida.setText("No se encontraron registros.\n");
        }
        }catch(Exception e){
            String error = e.getMessage();
            txtSalida.setForeground(Color.red);
            txtSalida.setText(error);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void crearNodos(DefaultMutableTreeNode raiz) {
		ArrayList<String> bases = new ArrayList<String>();
		
		try {
			Connection con = Conexion.getMainConnection(); 					
			DatabaseMetaData meta = con.getMetaData();
			ResultSet res = meta.getCatalogs();
			//ResultSet res = meta.getTables(null, null, "%", new String[] {"TABLE"});
            while (res.next()) {
               bases.add(res.getString("TABLE_CAT"));
               //bases.add(res.getString("TABLE_NAME") + "-" + res.getString("TABLE_CAT") + "-" + res.getString(3));
            }
            res.close();
            con.close();
		} catch (SQLException e){
			JOptionPane.showMessageDialog(null, e);
		}
		
		
	    DefaultMutableTreeNode bdd = null;
	    DefaultMutableTreeNode tabla = null;
	    
	    for(String base : bases){
	    	bdd = new DefaultMutableTreeNode(base);
		    raiz.add(bdd);
	    }
	}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmParser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmParser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmParser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmParser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmParser().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree dbTree;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblTablas;
    private javax.swing.JTextArea txtEntrada;
    private javax.swing.JTextArea txtSalida;
    private javax.swing.JTextArea txtTablas;
    // End of variables declaration//GEN-END:variables
}
